### ISSUE TITLE
Change Password Feature

### ISSUE THREAD

**Issue by ryanwrtong** [graceoncampus/goc-web#56]
## Description
Currently, there is no way to change a user's password after they have logged in. The only way to reset a password is if a user clicks "Forgot Password" before logging in. We want to add a "Change Password" feature in the "Edit Profile" tab so that a user can update their password after logging in. This can take the form of a button that upon clicking will navigate them to a new change password page, where they will need to enter their old password, enter their new password, and re-enter/confirm their new password. After clicking submit, our site should invoke Firebase Auth SDK to update a user: Using Firebase Admin API (https://firebase.google.com/docs/auth/admin/manage-users#update_a_user) or Firebase Web User API (https://firebase.google.com/docs/auth/web/manage-users#set_a_users_password). Admin API manages users with elevated privileges, and is what we use to create users, so I suggest using that. However, if the User API is easier, feel free to use that as well.

## Acceptance Criteria
- New "ChangePassword" view exists and is reachable
- "Change password" button exists in Edit Profile page that navigates to "ChangePassword" view
- "ChangePassword" view should include: Top navigation bar, a heading that says "Change Password", 3 text inputs where users can enter old, new, and confirm passwords, a submit button, and the footer.
- Check to confirm that old password is correct (https://firebase.google.com/docs/auth/web/manage-users#re-authenticate_a_user)
- Check to confirm that new password and old password are different
- Check to confirm that old password and confirm password are matching
- Clicking submit button updates the user's password in Firebase and displays error if it fails.
- Some sort of indication (having the button turn green and say success -- just like how Update Profile does it) to indicate that password successfully changed.

**Comment by eriadnus** [comment]
d o n e
