### ISSUE TITLE
Repeated Sermons in GOC sermons page

### ISSUE THREAD

**Issue by isaachui** [graceoncampus/goc-web#6]
On the goc sermons page, every sermon (it seems) is repeated 3 times

**Comment by isaachui** [comment]
@ryanwrtong I believe this is fixed?

**Comment by ryanwrtong** [comment]
Running `node load-sermons.js` in /devscripts works removes duplicates, but then sometimes they reappear. Could possibly be happening through the cron job or when `node update-sermons.js` is called in config.yml

**Comment by ryanwrtong** [comment]
Fixed by removing `node update-sermons.js`.
