### ISSUE TITLE
Sermon Audio Pause after Playing Another

### ISSUE THREAD

**Issue by ryanwrtong** [graceoncampus/goc-web#60]
When a sermon recording is currently being played on the GOC website and a user clicks to play another recording, the first recording does not pause, but rather both sermons play at the same time. What we would like is for the audio to pause when another recording is played so that the user is only listening to one sermon at a time.

Find out if it is possible to add this feature and add it. The audio gets played via the `<audio>` tag in sermons.ejs, with the source being the URI for each sermon (stored in Firestore).

**Comment by eriadnus** [comment]
Fixed by @dbranda0 in **Sermon audio #63**
